---
title: "HW #2"
name: 'Mitchell Bosley'
date: 15 May 2019
output: pdf_document
---

# Part IV

Hospital visit simulation:

```{r}

# Functions
################

# Time until next patient arrives
patient_Arrival <- function() { round(rpois(n=1, lambda=5), 0) }

# Time spent with each patient
appointment_Length <- function() { round(runif(n=1, min=5, max=20), 0) }

# function checks whether a doctor is available
doc_Availability <- function(x) { return(which(x[1] == 0)) }

# construct time measure
calc_Minutes <- function(hours) { return(60 * hours) }

# intake walk-in patient
patient_Intake <- function(totalPatients, waitLengths, doctors, waitingRoom) {
    docsAvailable <- which( lapply(doctors, doc_Availability) == 1 )
    if (length(docsAvailable) > 0) {
        doc <- sample(docsAvailable, 1)
        doctors[[doc]]$patient <- 1
        doctors[[doc]]$apptlength <- appointment_Length()
        waitLengths <- c(waitLengths, 0)
    } else {
        waitingRoom <- rbind(c('patient', 0), waitingRoom)
    }
    totalPatients <- totalPatients + 1
    nextPatient <- patient_Arrival()
    return(list(totalPatients = totalPatients, nextPatient = nextPatient,
                waitLengths = waitLengths, doctors = doctors, waitingRoom = waitingRoom))
}

# time moves forward by 1 minute
time_Change <- function(time, waitLengths, doctors, minutes, waitingRoom) {
    # Countdown until next patient
    nextPatient <- nextPatient - time
    # Countdown for current appointments, reset
    # doctor if appointment ends
    for (i in 1:length(doctors)) {
        if (doctors[[i]]$apptlength != 0) {
            doctors[[i]]$apptlength <- doctors[[i]]$apptlength - time
        } else {
            doctors[[i]]$patient <- 0
        }
    }
    # Assign longest waiter to available doctor
    docsAvailable <- which( lapply(doctors, doc_Availability) == 1 )
    for (i in 1:nrow(waitingRoom)){
        if (length(docsAvailable) > 0 & nrow(waitingRoom) != 0) {
            doc <- sample(docsAvailable, 1)
            doctors[[doc]]$patient <- 1
            doctors[[doc]]$apptlength <- appointment_Length()
            # Choose the person with the longest wait time.
            waitNum <- which.max(waitingRoom[, 2])
            waitLengths <- c(waitLengths, max(as.numeric(waitingRoom[, 2])))
            waitingRoom <- waitingRoom[-waitNum,]
        }
    }
    # increase wait time by 1 minute for each person in wait room
    waitingRoom[, 2] <- as.numeric(waitingRoom[, 2]) + time
    # reduce remaining minutes for accepting new patients
    minutes <- minutes - time
    return(list(waitingRoom = waitingRoom, waitLengths = waitLengths,
                nextPatient = nextPatient, doctors = doctors,
                minutes = minutes))
}

# Main Loop
##############

# Create doctors
doctors <- list( list('patient' = 0, 'apptlength' = 0),
                 list('patient' = 0, 'apptlength' = 0),
                 list('patient' = 0, 'apptlength' = 0) )

# Create waiting room
waitingRoom <- data.frame(matrix(ncol=2, nrow=0))
colnames(waitingRoom) <- c('waiting_patients', 'wait_time')

# containers
totalPatients <- 0
waitLengths <- c()

minutes <- calc_Minutes(hours=7)
nextPatient <- 0

# main loop
while (length(which(lapply(doctors, doc_Availability) == 1)) != 3 |
        nrow(waitingRoom) != 0 | minutes > 0) {
    if (nextPatient == 0 & minutes > 0) {
        intakeInfo <- patient_Intake(totalPatients, waitLengths, doctors, waitingRoom)
        nextPatient <- intakeInfo$nextPatient
        totalPatients <- intakeInfo$totalPatients
        waitLengths <- intakeInfo$waitLengths
        doctors <- intakeInfo$doctors
        waitingRoom <- intakeInfo$waitingRoom
        }
    timeInfo <- time_Change(time=1, waitLengths, doctors, minutes, waitingRoom)
    waitLengths <- timeInfo$waitLengths
    nextPatient <- timeInfo$nextPatient
    doctors <- timeInfo$doctors
    minutes <- timeInfo$minutes
    waitingRoom <- timeInfo$waitingRoom
}

# simulating main loop 1000 times:
trials <- 1000
results <- data.frame(matrix(nrow=trials, ncol=4))
colnames(results) <- c('avg_wait', 'count_wait', 'patient_count', 'minutes_past')
for (j in 1:trials) {
    doctors <- list( list('patient' = 0, 'apptlength' = 0),
                     list('patient' = 0, 'apptlength' = 0),
                     list('patient' = 0, 'apptlength' = 0) )
    waitingRoom <- data.frame(matrix(ncol=2, nrow=0))
    colnames(waitingRoom) <- c('waiting_patients', 'wait_time')
    totalPatients <- 0
    waitLengths <- c()
    minutes <- calc_Minutes(hours=7)
    nextPatient <- 0
  while (length(which(lapply(doctors, doc_Availability) == 1)) != 3 |
        nrow(waitingRoom) != 0 | minutes > 0) {
    if (nextPatient == 0 & minutes > 0) {
        intakeInfo <- patient_Intake(totalPatients, waitLengths, doctors, waitingRoom)
        nextPatient <- intakeInfo$nextPatient
        totalPatients <- intakeInfo$totalPatients
        waitLengths <- intakeInfo$waitLengths
        doctors <- intakeInfo$doctors
        waitingRoom <- intakeInfo$waitingRoom
        }
    timeInfo <- time_Change(time=1, waitLengths, doctors, minutes, waitingRoom)
    waitLengths <- timeInfo$waitLengths
    nextPatient <- timeInfo$nextPatient
    doctors <- timeInfo$doctors
    minutes <- timeInfo$minutes
    waitingRoom <- timeInfo$waitingRoom
  }
results[j,] <- c(mean(waitLengths[waitLengths!=0]), sum(waitLengths > 0), totalPatients, abs(minutes))
}
```

# 6.3
```{r}
# Create MCMC function:
mcmc <- function(p, states, burnin, runs) {

    # burn-in:
    value <- sample(states, 1)
    for (i in 1:burnin) {
        if (value == 1) {
            draw <- rbinom(1, 1, p[1,2])
            if (draw == 1) {
                value <- 2 
            } 
        } else {
            draw <- rbinom(1, 1, p[2, 1])
            if (draw == 1) {
                value <- 1
            }
        }
    }

    # storing results
    values <- rep(NA, runs)
    for (i in 1:runs) {
        if (value == 1) {
            draw <- rbinom(1, 1, p[1,2])
            if (draw == 1) {
                value <- 2 
            }
        } else {
            draw <- rbinom(1, 1, p[2, 1])
            if (draw == 1) {
                value <- 1
            }
        }
        values[i] <- value
    }
    return(values)
}

# Create transition matrix

a_1 <- 0.75
a_2 <- 0.25
b_1 <- 0.125
b_2 <- 0.875
p <- matrix(data=c(a_1, a_2, b_1, b_2), nrow=2, byrow=TRUE)

# specify number of states. (note that this code will only work for 2)

states <- c(1,2)

# run algorithm 
runs <- seq(1, 2000)
pct_results <- rep(NA, length(runs))
for (i in runs){
    results <- mcmc(p, states, burnin=100, runs=i)
    pct_results[i] <- sum(results[results==1]) / i 
}

sequence <- seq(5, 2000, 5) 
plot(x=runs[sequence], y=pct_results[sequence], type="l", xlab="runs",
ylab="cumulative mean", main="Convergence of the Markov Chain to the Invariant Distribution")
```

```{r}
# random walk function
walk <- function(p, q, r, steps){
    outcome <- rep(NA, steps)
    place <- 0
    for (i in 1:steps){
        step <- which(rmultinom(1, 1, c(p, q, r))==1)
        if (step == 1) place <- place + 1
        if (step == 3) place <- place - 1
        outcome[i] <- place
    }
    return(outcome)
}

# run function
steps <- 1000
p <- 0.4
q <- 0.3
r <- 0.3
results <- walk(p, q, r, steps)

# plot function
plot(x=1:steps, y=results, type='l', xlab="step number",
     ylab="cumulative steps", main="Random Walk")

```
